Q 1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [ ]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50])

#  Addition
arr_add = arr + 2
print("After addition of 2:", arr_add)

# b) Multiplication
arr_mul = arr * 3
print("After multiplication by 3:", arr_mul)

# c) Division
arr_div = arr / 2
print("After division by 2:", arr_div)


After addition of 2: [12 22 32 42 52]
After multiplication by 3: [ 30  60  90 120 150]
After division by 2: [ 5. 10. 15. 20. 25.]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
arr_rev = np.array([1, 2, 3, 6, 4, 5])[::-1]
print("Reversed array:", arr_rev)

Reversed array: [5 4 6 3 2 1]


In [ ]:
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = values[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

x_value, x_indices = most_frequent(x)
y_value, y_indices = most_frequent(y)

print(f"Most frequent value in x: {x_value}, Indices: {x_indices}")
print(f"Most frequent value in y: {y_value}, Indices: {y_indices}")


Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [1]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(arr[0, 1])
print(arr[2, 0])


20
70


Q 3 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [2]:
import numpy as np

# Create a 1-D array with 25 evenly spaced numbers from 10 to 100
your_name = np.linspace(10, 100, 25)

# Print array properties
print("Array:", your_name)
print("Dimensions of the array:", your_name.ndim)
print("Shape of the array:", your_name.shape)
print("Total number of elements:", your_name.size)
print("Data type of each element:", your_name.dtype)
print("Total bytes consumed by the array:", your_name.nbytes)

# Find the "transpose" using reshape
reshaped_array = your_name.reshape(25, 1)
print("\nReshaped Array (Transpose using reshape):\n", reshaped_array)

# Check if we can use T attribute for transpose
transposed_array = your_name.T
print("\nTransposed Array using T attribute:\n", transposed_array)

# Explanation
if np.array_equal(your_name, transposed_array):
    print("\n The T attribute does not work for 1-D arrays, as they remain unchanged!")


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total number of elements: 25
Data type of each element: float64
Total bytes consumed by the array: 200

Reshaped Array (Transpose using reshape):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed Array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

 The T attribute does not work for 1-D arrays, as they remain unchanged!


Q 4 Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [3]:
import numpy as np
ucs420_Akanksha = np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])

# Computing mean, median, max, min, and unique elements
mean_value = np.mean(ucs420_Akanksha)
median_value = np.median(ucs420_Akanksha)
max_value = np.max(ucs420_Akanksha)
min_value = np.min(ucs420_Akanksha)
unique_elements = np.unique(ucs420_Akanksha)

# Printing results
print("Original Array (ucs420_Akanksha):\n", ucs420_Akanksha)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max Value:", max_value)
print("Min Value:", min_value)
print("Unique Elements:", unique_elements)

# Reshaping to 4 rows and 3 columns
reshaped_ucs420_Akanksha = ucs420_Akanksha.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_Akanksha)

# Resizing to 2 rows and 3 columns (this changes the original array)
resized_ucs420_Akanksha = np.resize(ucs420_Akanksha, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_Akanksha)


Original Array (ucs420_Akanksha):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max Value: 90
Min Value: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


NameError: name 'resized_ucs420_Akanksha' is not defined